### PR TITLE
feat: update turf details

### PR DESCRIPTION
**Pull request by MuhammedFayazTS**
- update turf details
- update turf image
- TODO: update turf documents

### CODE REVIEW

**Comment by sameekshasam** [comment]
how to run the project

**Comment by sameekshasam** [comment]
can you send .env file.....

**Comment by MuhammedFayazTS** [comment]
@sameekshasam 
I am modifying some functionalities so it will not run now . The updation will be completed in few days.

**Comment by sameekshasam** [comment]
can you send the .env file

**Pull request merged**
